# Generated by Django 6.0.2 on 2026-02-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('component_type', models.CharField(choices=[('assembly', 'Ensemble'), ('sub_assembly', 'Sous-ensemble'), ('part', 'Pièce'), ('raw_material', 'Matière première')], default='part', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_components', to='bom.component')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='bom.component')),
            ],
            options={
                'ordering': ['parent__reference'],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
